name: yash_s_application1
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.0
  connectivity_plus: ^5.0.2
  country_list_pick: ^1.0.1+6
  language_code: ^0.5.3+2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Antonio
      fonts: 
        - asset: assets/fonts/AntonioRegular.ttf
          weight: 400
    - family: Aclonica
      fonts: 
        - asset: assets/fonts/AclonicaRegular.ttf
          weight: 400
    - family: Actor
      fonts: 
        - asset: assets/fonts/ActorRegular.ttf
          weight: 400
